# Generated by Django 2.1.5 on 2019-03-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lectures',
            name='para',
            field=models.ManyToManyField(to='social.para'),
        ),
        migrations.AlterField(
            model_name='para',
            name='head',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='heading',
        ),
        migrations.DeleteModel(
            name='practice',
        ),
    ]
